FROM rust:latest

COPY ./server/src ./server/src
COPY ./server/Cargo.lock ./server/Cargo.lock
COPY ./server/Cargo.toml ./server/Cargo.toml
COPY ./server/words_of_wisdom.txt ./server/words_of_wisdom.txt
COPY ./lib ./lib